#!/bin/sh

egrep -o "../assets/.*svg" $1 | while read svgFile
do
		base64File=$(cat $svgFile | base64)
		sed -i_ "s|$svgFile|data:image/svg+xml;base64,$base64File|" $1
done

egrep -o "./assets/.*png" $1 | while read pngFile
do
		base64File=$(cat $pngFile | base64)
		sed -i_ "s|$pngFile|data:image/png;base64,$base64File|" $1
done
